task:
  name: Build
  timeout_in: 180m
  container:
    image: ubuntu:latest
    cpu: 8
    memory: 16G

  build_script:
    - apt update -y
    - apt upgrade -y
    - apt install curl git python-is-python2 python3 -y
    - curl -o /bin/repo https://storage.googleapis.com/git-repo-downloads/repo
    - chmod +x /bin/repo
    - mkdir android
    - cd android
    - git config --global user.name "Myst33d"
    - git config --global user.email "notmyst33d@gmail.com"
    - repo init -u https://android.googlesource.com/platform/manifest -b android-12.1.0_r1 --depth=1
    - git clone https://github.com/phhusson/treble_manifest .repo/local_manifests -b android-12.0
    - repo sync -c -j1 --fail-fast --force-sync --no-clone-bundle --no-tags
    - cd device/phh/treble
    - bash generate.sh
    - cd ../../../
    - . build/envsetup.sh
    - lunch treble_arm64_bvN-userdebug
    - make RELAX_USES_LIBRARY_CHECK=true BUILD_NUMBER=$rom_fp -j8 systemimage
